before_install:
  - sudo apt-get update
install:
    - sudo pip3 install tox-travis
    - sudo pip3 install -r requirements.txt
language:
  - python
python:
  - "3.6"
script:
    - flask run &
    - tox
